[versions]
# Project version
tars = "2.0.0"

# Java
java = "17"

# Core dependencies
netty = "4.2.10.Final"
netty-tcnative = "2.0.75.Final"
guava = "30.1-jre"
gson = "2.8.6"
slf4j = "1.7.30"

# Logging
logback = "1.2.3"
log4j2 = "2.11.1"

# Spring
spring = "4.2.9.RELEASE"
spring-boot-1x = "1.5.8.RELEASE"
spring-boot-2x = "2.0.3.RELEASE"

# Spring Cloud
eureka-client = "1.4.9"
spring-cloud-netflix-eureka = "1.3.1.RELEASE"
spring-cloud-commons = "1.2.2.RELEASE"

# Tracing
brave = "5.1.0"
brave-opentracing = "0.31.1"
zipkin-reporter = "2.7.4"

# Apache Commons
commons-lang = "2.6"
commons-io = "2.7"
commons-codec = "1.6"
commons-cli = "1.2"
commons-compress = "1.19"

# Testing
junit = "4.13.1"
hamcrest = "1.3"
assertj = "3.9.0"

# Servlet
servlet-api = "3.1.0"

# HTTP
httpcore = "4.3.2"

# Jakarta
jakarta-annotation = "2.1.1"

# ANTLR (for tars-gradle-plugin)
antlr = "3.5"

# Plexus
plexus-utils = "3.0.20"
plexus-interpolation = "1.21"

# Misc
sysout-over-slf4j = "1.0.2"

[libraries]
# Netty
netty-all = { module = "io.netty:netty-all", version.ref = "netty" }
netty-tcnative = { module = "io.netty:netty-tcnative", version.ref = "netty-tcnative" }

# Guava & Gson
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# Logging
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j2" }

# Spring Boot 1.x (for tars-spring)
spring-boot-starter-v1 = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot-1x" }
spring-boot-configuration-processor-v1 = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot-1x" }

# Spring Boot 2.x (for tars-spring-boot-starter, tars-http-extension)
spring-boot-starter-v2 = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot-2x" }
spring-boot-configuration-processor-v2 = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot-2x" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring-boot-2x" }

# Spring Cloud
eureka-client = { module = "com.netflix.eureka:eureka-client", version.ref = "eureka-client" }
spring-cloud-netflix-eureka-client = { module = "org.springframework.cloud:spring-cloud-netflix-eureka-client", version.ref = "spring-cloud-netflix-eureka" }
spring-cloud-commons = { module = "org.springframework.cloud:spring-cloud-commons", version.ref = "spring-cloud-commons" }

# Tracing
zipkin-sender-kafka11 = { module = "io.zipkin.reporter2:zipkin-sender-kafka11", version.ref = "zipkin-reporter" }
zipkin-sender-kafka08 = { module = "io.zipkin.reporter2:zipkin-sender-kafka08", version.ref = "zipkin-reporter" }
zipkin-sender-urlconnection = { module = "io.zipkin.reporter2:zipkin-sender-urlconnection", version.ref = "zipkin-reporter" }
brave-opentracing = { module = "io.opentracing.brave:brave-opentracing", version.ref = "brave-opentracing" }

# Apache Commons
commons-lang = { module = "commons-lang:commons-lang", version.ref = "commons-lang" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-cli = { module = "commons-cli:commons-cli", version.ref = "commons-cli" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }

# Servlet
servlet-api = { module = "javax.servlet:javax.servlet-api", version.ref = "servlet-api" }

# HTTP
httpcore = { module = "org.apache.httpcomponents:httpcore", version.ref = "httpcore" }

# Jakarta
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }
hamcrest-all = { module = "org.hamcrest:hamcrest-all", version.ref = "hamcrest" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

# ANTLR
antlr = { module = "org.antlr:antlr", version.ref = "antlr" }

# Plexus
plexus-utils = { module = "org.codehaus.plexus:plexus-utils", version.ref = "plexus-utils" }
plexus-interpolation = { module = "org.codehaus.plexus:plexus-interpolation", version.ref = "plexus-interpolation" }

# Misc
sysout-over-slf4j = { module = "uk.org.lidalia:sysout-over-slf4j", version.ref = "sysout-over-slf4j" }

[bundles]
tracing = ["zipkin-sender-kafka11", "zipkin-sender-kafka08", "zipkin-sender-urlconnection", "brave-opentracing"]
commons = ["commons-lang", "commons-io", "commons-codec", "commons-cli", "commons-compress"]

[plugins]
